# prometheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['localhost:9093']
#rule_files:
#  - 'alert.rules'
